---
# travis-ci config for pipdeptree

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - graphviz
before_install:
  - pip install -U pip>=8.0.2
  - pip install pytest
  - pip install graphviz
install: pip install .
script: pytest -v tests/test_pipdeptree.py
sudo: false
