name: check
on:
  push:
  pull_request:
  schedule:
  - cron: "0 8 * * *"

jobs:
  test:
    name: Test on ${{ matrix.py }} under ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
        - Ubuntu
        py:
        - 3.9-dev
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 3.4
        - 2.7
        - pypy3
        - pypy2
    steps:
    - name: Setup graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Setup python for tox
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install tox
      run: python -m pip install tox
    - name: Setup python for test ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - uses: actions/checkout@v2
    - name: Pick tox environment to run
      run: |
        import subprocess; import json
        major, minor, impl = json.loads(subprocess.check_output(["python", "-c", "import json; import sys; import platform; print(json.dumps([sys.version_info[0], sys.version_info[1], platform.python_implementation()]));"], universal_newlines=True))
        print('::set-env name=TOXENV::' + ("py" if impl == "CPython" else "pypy") + ("{}{}".format(major, minor) if impl == "CPython" else ("3" if major == 3 else "")))
      shell: python
    - name: Setup test suite
      run: tox -vv --notest
    - name: Run test suite
      run: tox --skip-pkg-install
